elasticsearch_config: |
  network.host: {{ ansible_host }}
  discovery.seed_hosts: [ "10.0.1.2", "10.0.1.3", "10.0.1.4" ]
kibana_config: |
  elasticsearch.hosts: [ "https://10.0.1.2:9200", "https://10.0.1.3:9200", "https://10.0.1.4:9200" ]
  server.host: "0.0.0.0"
  server.port: 5601
  elasticsearch.ssl.verificationMode: none
kibana_ssl_config: |
  server.ssl.enabled: true
  server.ssl.certificate: /etc/kibana/certs/kibana-cert.crt
  server.ssl.key: /etc/kibana/certs/kibana-key.key
metricbeat_config: |
  setup.kibana:
    host: "http://10.0.1.2:5601"
  output.elasticsearch:
    hosts: ["https://10.0.1.2:9200", "https://10.0.1.3:9200", "https://10.0.1.4:9200"]
    username: "elastic"
    password: "{{ elastic_password }}"
    ssl.verification_mode: none
