apiVersion: v1
kind: Service
metadata:
  labels:
    app: exam
  name: exam-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: exam
  type: LoadBalancer
