- name: Install Kibana on Ubuntu 22.04 LTS
  apt:
    update_cache: yes
    name: kibana
    state: present

- name: Generate enrollment token for Kibana nodes.
  shell: /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
  register: kibana_token_node
  when: inventory_hostname in groups["master_elk_server"]

- name: Display the Kibana token
  debug:
    msg: "Kibana Token: {{ kibana_token_node.stdout }}"
  when: inventory_hostname in groups["master_elk_server"]

- name: Keep Kibana tokens on different servers.
  copy:
    content: "{{ hostvars[groups['kibana_server'][0]]['kibana_token_node']['stdout'] }}"
    dest: /etc/kibana/kibana_token_node.txt
  loop: "{{ groups['kibana_server'] }}"
  when:
    - inventory_hostname in groups["kibana_server"]
    - inventory_hostname != item
  delegate_to: "{{ item }}"

- name: set a variable using a file.
  shell: cat /etc/kibana/kibana_token_node.txt
  register: kibana_token
  when: inventory_hostname in groups["kibana_server"]

- name: Register/Enrolling kibana
  shell: /usr/share/kibana/bin/kibana-setup --enrollment-token {{ kibana_token.stdout }} 
  when: inventory_hostname in groups["kibana_server"]

- name: Delete line elasticsearch.hosts
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^elasticsearch.hosts:'
    line: '#'
  when: inventory_hostname in groups["kibana_server"]

- name: Config Kibana
  blockinfile:
    path: /etc/kibana/kibana.yml
    block: "{{ kibana_config }}"
    marker: "# {mark} Kibana configuration"
    backup: yes
  when: inventory_hostname in groups["kibana_server"]

- name: Start kibana service
  service:
    name: kibana
    state: started
  when: inventory_hostname in groups["kibana_server"]