- name: Update the server and install dependencies
  apt:
    name: apt-transport-https
    update_cache: yes

- name: Add ElasticSearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg

- name: Add ElasticSearch repository
  shell: echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic-8.x.list
